# Generated by Django 5.0.6 on 2024-06-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('Playid', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing'), ('played', 'Played')], default='pending', max_length=100)),
                ('songid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.song')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('historyid', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.user')),
            ],
        ),
    ]
