# Generated by Django 5.0.6 on 2024-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
